//
//  ViewController.m
//
//  Author: Katie Soto
//  Project: iPhone Discount Calculator
//  Author's Email: KReneSoto@gmail.com
//  Author's Phone: (714) 213-2228
//  Date Created: 9/2012
//  Class: CSUF CPSC 491T - iPhone Mobile App Development
//  Professor: Michael Shafae
//  Copyright (c) 2012 Katie Soto. All rights reserved.
//  Problem Statement: Write an iPhone Application that is used to calculate
//      discounts. A user inputs the original price, a discount percentage,
//      an additional discount percentage, and a tax rate. Once they press
//      "calculate", the amount they saved from the first discount, the
//      amount they saved from the second discount, the amount of taxes
//      generated, the total price, and the total amount saved is displayed.
//      Also, after the calculations have been shown, a user can view a
//      graphical representation of how the money has been allocated through
//      a bar graph.
//  File Description: This file has been generated by XCode and has not
//      been modified.

/* XCode Generated */
#import "AppDelegate.h"

@implementation AppDelegate

@synthesize window = window;

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    return YES;
}
							
- (void)applicationWillResignActive:(UIApplication *)application
{
}

- (void)applicationDidEnterBackground:(UIApplication *)application
{

}

- (void)applicationWillEnterForeground:(UIApplication *)application
{

}

- (void)applicationDidBecomeActive:(UIApplication *)application
{

}

- (void)applicationWillTerminate:(UIApplication *)application
{

}

@end
